### ISSUE TITLE
Package not generated correctly in test files

### ISSUE THREAD

**Issue by jontto** [viritin/archetype-vaadin-addon#1]
The project created from the archetype can't be compiled, because the it does not take into account the entered package correctly. 

It leaves 
import org.test.ClearableTextBox; in ClearableTextBoxTest
import org.test.BasicJavaScriptComponentUsageUI; in BasicJavaScriptComponentUsageIT
import org.test.jsexample.MyJavaScriptComponent; in BasicJavaScriptComponentUsageUI

**Comment by jontto** [comment]
71047fd48bb43905f64e73e66b9423cbd2ce1307 seems to have fixed this. Thanks!

**Comment by mstahv** [comment]
Yep, @samie noticed that yesterday as well! Thanks!
